# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClusterDxf
                                 A QGIS plugin
 Export clusters to DXF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-16
        copyright            : (C) 2020 by Basil Eric Rabi
        email                : basil.rabi@tmc.nickelasia.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Basil Eric Rabi'
__date__ = '2020-09-16'
__copyright__ = '(C) 2020 by Basil Eric Rabi'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ClusterDxf class from file ClusterDxf.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cluster_dxf import ClusterDxfPlugin
    return ClusterDxfPlugin()
